standalone_tags:
  [
    {id: 34, size: 0.02},
    {id: 35, size: 0.02},

    {id: 44, size: 0.02},
    {id: 45, size: 0.02},

    {id: 36, size: 0.02},
    {id: 37, size: 0.02},

    {id: 32, size: 0.02},
    {id: 33, size: 0.02},

    {id: 42, size: 0.02},
    {id: 43, size: 0.02},

    {id: 40, size: 0.02},
    {id: 41, size: 0.02},
    
    {id: 38, size: 0.02},
  ]
